// backend/src/utils/cropKnowledgeBase.js
// ═══════════════════════════════════════════════════════════════════
// Comprehensive crop knowledge base for the rule-based ML engine.
//
// Each crop entry defines:
//   optimal {}    → ideal ranges for scoring (1.0 score at midpoint)
//   tolerance {}  → outer boundary — outside = score approaches 0
//   seasons []    → which seasons this crop fits
//   soilTypes []  → compatible soil types
//   states []     → suitable Indian states (empty = pan-India)
//   agronomy {}   → farming guidance for the recommendation output
//   market {}     → demand, price stability, risk
//   yield {}      → expected production data
// ═══════════════════════════════════════════════════════════════════

export const CROP_DB = {

  wheat: {
    name:'Wheat', emoji:'🌾', category:'Cereal',
    seasons:['rabi'],
    soilTypes:['loamy','clay-loam','alluvial'],
    states:['Punjab','Haryana','Uttar Pradesh','Madhya Pradesh','Rajasthan','Gujarat','Bihar'],
    optimal:  {N:[60,120], P:[30,60],  K:[30,50],  ph:[6.0,7.5], temp:[10,25], humidity:[40,70], rainfall:[50,100]},
    tolerance:{N:[0,200],  P:[0,100], K:[0,100],  ph:[5.5,8.5], temp:[5,30],  humidity:[20,90], rainfall:[25,200]},
    agronomy:{
      sowingTime:'October–November (Rabi)',
      harvestTime:'March–April (110–130 days)',
      waterNeeds:'Moderate — 4–5 irrigations (450–650 mm)',
      fertilizerTip:'Apply 120:60:40 kg/ha N:P:K. Split N: 50% basal, 25% at CRI stage, 25% at tillering.',
      irrigationTip:'Critical stages: Crown Root Initiation (20–25 DAS), Tillering, Jointing, Flowering, Grain Fill.',
      organicTip:'Apply FYM 10 t/ha 3–4 weeks before sowing to improve soil structure.',
      tips:['Use certified disease-resistant varieties (HD-2967, GW-322, Raj-4120)','Seed treatment with Thiram 2 g/kg seed','Apply Boron 0.5 g/L foliar spray at flag-leaf for better grain filling','Timely sowing (Nov 1–15) gives highest yields'],
    },
    market:{demand:'High', priceStability:'Very High', mspAvailable:true, exportPotential:'High', riskLevel:'Low'},
    yield:{min:25, max:55, unit:'quintals/acre', avgIndia:35},
  },

  rice: {
    name:'Rice', emoji:'🌾', category:'Cereal',
    seasons:['kharif'],
    soilTypes:['clay','clay-loam','alluvial'],
    states:['West Bengal','Uttar Pradesh','Punjab','Andhra Pradesh','Telangana','Tamil Nadu','Odisha','Bihar'],
    optimal:  {N:[80,120], P:[30,50],  K:[30,50],  ph:[5.5,6.5], temp:[20,35], humidity:[65,85], rainfall:[150,300]},
    tolerance:{N:[0,200],  P:[0,100], K:[0,100],  ph:[4.5,8.0], temp:[15,40], humidity:[40,95], rainfall:[100,500]},
    agronomy:{
      sowingTime:'June–July (Kharif)',
      harvestTime:'October–November (130–160 days)',
      waterNeeds:'High — 1200–2000 mm seasonal water requirement',
      fertilizerTip:'Apply 100:50:50 kg/ha N:P:K. Split N in 3: Basal, Tillering, Panicle initiation.',
      irrigationTip:'Maintain 5 cm standing water till panicle initiation. Drain 7–10 days before harvest.',
      organicTip:'Incorporate green manure (Dhaincha) 45 days before transplanting.',
      tips:['Transplant 25–30 day old seedlings for Sona Masuri','SRI method reduces water by 40%','Apply Zinc Sulphate 25 kg/ha in Zn-deficient soils','Scout for Brown Planthopper (BPH) weekly'],
    },
    market:{demand:'Very High', priceStability:'High', mspAvailable:true, exportPotential:'High', riskLevel:'Low'},
    yield:{min:20, max:60, unit:'quintals/acre', avgIndia:35},
  },

  maize: {
    name:'Maize (Corn)', emoji:'🌽', category:'Cereal',
    seasons:['kharif','rabi','zaid'],
    soilTypes:['loamy','sandy-loam','alluvial','red'],
    states:[],
    optimal:  {N:[80,120], P:[40,60],  K:[40,60],  ph:[5.8,7.0], temp:[21,27], humidity:[50,75], rainfall:[60,110]},
    tolerance:{N:[0,200],  P:[0,120], K:[0,120],  ph:[5.0,8.0], temp:[15,35], humidity:[30,90], rainfall:[30,200]},
    agronomy:{
      sowingTime:'June–July (Kharif) / October–November (Rabi)',
      harvestTime:'September–October / February–March (85–110 days)',
      waterNeeds:'Moderate — 5–6 irrigations (500–600 mm)',
      fertilizerTip:'Apply 120:60:40 kg/ha N:P:K. Top dress 30 kg N/acre at knee-high stage.',
      irrigationTip:'Critical: Tasseling and silking. Avoid stress at these periods.',
      organicTip:'Apply vermicompost 2 t/acre at sowing.',
      tips:['Use hybrid seeds (HQPM-1, NK-6240) for 30–40% higher yield','Avoid waterlogging at seedling stage','Apply Zinc Sulphate 25 kg/ha if white strip symptoms appear','Scout for Fall Armyworm from V3 stage'],
    },
    market:{demand:'High', priceStability:'High', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Low'},
    yield:{min:24, max:56, unit:'quintals/acre', avgIndia:32},
  },

  bajra: {
    name:'Bajra (Pearl Millet)', emoji:'🌾', category:'Cereal',
    seasons:['kharif'],
    soilTypes:['sandy','sandy-loam','loamy'],
    states:['Rajasthan','Gujarat','Haryana','Maharashtra','Uttar Pradesh'],
    optimal:  {N:[40,80],  P:[20,40],  K:[20,40],  ph:[6.0,8.0], temp:[25,35], humidity:[30,60], rainfall:[30,75]},
    tolerance:{N:[0,150],  P:[0,80],  K:[0,80],   ph:[5.5,8.5], temp:[20,42], humidity:[15,80], rainfall:[15,150]},
    agronomy:{
      sowingTime:'June–July (Kharif onset)',
      harvestTime:'September–October (75–90 days)',
      waterNeeds:'Low — drought tolerant; 2–3 irrigations sufficient',
      fertilizerTip:'Apply 80:40:20 kg/ha N:P:K. Performs well even in marginal soils.',
      irrigationTip:'Pre-sowing and at tillering + flowering if dry spell.',
      organicTip:'FYM 5 t/acre improves yield on sandy soils.',
      tips:['Excellent for drought-prone areas and sandy soils','Hybrid varieties (HHB-67, GHB-558) give 25–30% more','Downy mildew is main disease — use resistant varieties','Can be intercropped with Groundnut'],
    },
    market:{demand:'Moderate', priceStability:'Moderate', mspAvailable:true, exportPotential:'Low', riskLevel:'Low'},
    yield:{min:12, max:28, unit:'quintals/acre', avgIndia:16},
  },

  chickpea: {
    name:'Chickpea (Gram/Chana)', emoji:'🫘', category:'Pulse',
    seasons:['rabi'],
    soilTypes:['loamy','clay-loam','black','alluvial'],
    states:['Madhya Pradesh','Rajasthan','Maharashtra','Uttar Pradesh','Andhra Pradesh','Gujarat'],
    optimal:  {N:[15,30],  P:[40,60],  K:[20,40],  ph:[6.0,7.5], temp:[15,25], humidity:[30,60], rainfall:[40,80]},
    tolerance:{N:[0,60],   P:[0,100], K:[0,80],   ph:[5.5,9.0], temp:[8,30],  humidity:[15,80], rainfall:[20,150]},
    agronomy:{
      sowingTime:'October–November',
      harvestTime:'February–March (95–110 days)',
      waterNeeds:'Low — 2–3 irrigations (300–400 mm)',
      fertilizerTip:'Apply 20:40:20 kg/ha. Rhizobium inoculation saves 20–30 kg N/ha.',
      irrigationTip:'Irrigate at flower initiation and pod filling. Avoid excess moisture.',
      organicTip:'Seed treatment with Rhizobium culture + PSB.',
      tips:['Fixes 40–80 kg N/ha — excellent for soil health','ICC-4958, GNG-1581, JG-11 are popular varieties','Chickpea Wilt (Fusarium) and Blight (Ascochyta) are major diseases','Avoid heavy black soils — prefers loamy/alluvial'],
    },
    market:{demand:'Very High', priceStability:'High', mspAvailable:true, exportPotential:'High', riskLevel:'Low'},
    yield:{min:8, max:20, unit:'quintals/acre', avgIndia:10},
  },

  pigeonpea: {
    name:'Pigeon Pea (Tur/Arhar)', emoji:'🫘', category:'Pulse',
    seasons:['kharif'],
    soilTypes:['loamy','red','black','sandy-loam'],
    states:['Maharashtra','Karnataka','Madhya Pradesh','Uttar Pradesh','Gujarat','Andhra Pradesh'],
    optimal:  {N:[20,40],  P:[30,50],  K:[20,40],  ph:[6.0,7.5], temp:[25,35], humidity:[40,70], rainfall:[75,120]},
    tolerance:{N:[0,80],   P:[0,80],  K:[0,80],   ph:[5.0,8.5], temp:[18,40], humidity:[20,90], rainfall:[40,250]},
    agronomy:{
      sowingTime:'June–July (Kharif)',
      harvestTime:'November–December (160–200 days)',
      waterNeeds:'Low to moderate — drought tolerant once established',
      fertilizerTip:'Starter: 20:50:20 kg/ha N:P:K + Rhizobium inoculation.',
      irrigationTip:'Irrigate at flowering (September) and pod filling (October).',
      organicTip:'Excellent N-fixer — 60–200 kg/ha N returned to soil.',
      tips:['Deep taproot — tolerates drought well','Great for intercropping with Sorghum or Cotton','ICPL-87119 (Asha) is Fusarium-wilt resistant','Long duration (200 days) — plan crop rotation carefully'],
    },
    market:{demand:'High', priceStability:'High', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Moderate'},
    yield:{min:6, max:18, unit:'quintals/acre', avgIndia:8},
  },

  groundnut: {
    name:'Groundnut', emoji:'🥜', category:'Oilseed',
    seasons:['kharif','rabi','zaid'],
    soilTypes:['sandy-loam','loamy','red'],
    states:['Gujarat','Andhra Pradesh','Telangana','Tamil Nadu','Karnataka','Maharashtra','Rajasthan'],
    optimal:  {N:[15,25],  P:[30,60],  K:[50,80],  ph:[6.0,7.0], temp:[25,35], humidity:[50,80], rainfall:[50,125]},
    tolerance:{N:[0,60],   P:[0,100], K:[0,120],  ph:[5.5,8.0], temp:[20,40], humidity:[30,90], rainfall:[30,200]},
    agronomy:{
      sowingTime:'June–July (Kharif) / January–February (Rabi)',
      harvestTime:'September–October (105–135 days)',
      waterNeeds:'Moderate — 6–8 irrigations; critical at pegging and pod development',
      fertilizerTip:'Apply 25:50:75 kg/ha N:P:K. Gypsum 500 kg/ha at flowering is CRITICAL.',
      irrigationTip:'Most critical: Pegging (35–40 DAS) and pod filling (75–100 DAS). Avoid waterlogging.',
      organicTip:'Apply FYM 5 t/acre. Rhizobium inoculation saves N cost.',
      tips:['Gypsum at flowering is THE most important input for pod filling','TG-37A, GJG-32 are popular Gujarat varieties','Earth up 30–35 DAS to help pegs penetrate soil','Aflatoxin risk if pods stored with >10% moisture — dry properly'],
    },
    market:{demand:'Very High', priceStability:'High', mspAvailable:true, exportPotential:'High', riskLevel:'Low'},
    yield:{min:12, max:32, unit:'quintals/acre', avgIndia:18},
  },

  mustard: {
    name:'Mustard (Rapeseed)', emoji:'🌼', category:'Oilseed',
    seasons:['rabi'],
    soilTypes:['loamy','sandy-loam','alluvial'],
    states:['Rajasthan','Haryana','Uttar Pradesh','Madhya Pradesh','West Bengal','Gujarat'],
    optimal:  {N:[60,100], P:[30,50],  K:[20,40],  ph:[6.0,7.5], temp:[10,25], humidity:[35,65], rainfall:[25,60]},
    tolerance:{N:[0,150],  P:[0,80],  K:[0,80],   ph:[5.5,8.0], temp:[5,35],  humidity:[15,80], rainfall:[15,120]},
    agronomy:{
      sowingTime:'October–November',
      harvestTime:'February–March (90–120 days)',
      waterNeeds:'Low to moderate — 3–4 irrigations',
      fertilizerTip:'Apply 80:40:40 kg/ha N:P:K. Sulphur 20 kg/ha improves oil content.',
      irrigationTip:'Apply at 30–35 DAS, at flowering (60 DAS), and pod filling (90 DAS).',
      organicTip:'Sulphur application is critical for oil quality.',
      tips:['Sulphur application dramatically improves oil quality — use SSP or Ammonium Sulphate','Aphid attack in February — monitor and spray Dimethoate if needed','Pusa Bold, RH-30, GM-3 are high-yielding varieties','Harvest when 75% pods turn yellowish-brown'],
    },
    market:{demand:'High', priceStability:'High', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Low'},
    yield:{min:8, max:20, unit:'quintals/acre', avgIndia:12},
  },

  soybean: {
    name:'Soybean', emoji:'🫘', category:'Oilseed',
    seasons:['kharif'],
    soilTypes:['loamy','clay-loam','black','alluvial'],
    states:['Madhya Pradesh','Maharashtra','Rajasthan','Karnataka','Telangana','Gujarat'],
    optimal:  {N:[20,40],  P:[50,80],  K:[40,60],  ph:[6.0,7.0], temp:[25,32], humidity:[55,80], rainfall:[75,125]},
    tolerance:{N:[0,80],   P:[0,120], K:[0,100],  ph:[5.5,8.0], temp:[18,38], humidity:[30,90], rainfall:[45,200]},
    agronomy:{
      sowingTime:'June–July (with onset of Kharif rains)',
      harvestTime:'October–November (90–120 days)',
      waterNeeds:'Moderate — 5–6 irrigations if rainfall inadequate',
      fertilizerTip:'Apply 30:60:40 kg/ha. Rhizobium + PSB seed inoculation.',
      irrigationTip:'Critical at pod filling (R4) and seed filling (R6) stages.',
      organicTip:'Green manuring before sowing improves yield by 15–20%.',
      tips:['Do NOT apply excess N — reduces nodulation','Rhizobium inoculation is essential','JS-335, NRC-7, MACS-450 are leading varieties','Yellow Mosaic Virus — control whitefly vector'],
    },
    market:{demand:'High', priceStability:'High', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Low'},
    yield:{min:10, max:24, unit:'quintals/acre', avgIndia:14},
  },

  castor: {
    name:'Castor', emoji:'🌿', category:'Oilseed',
    seasons:['kharif'],
    soilTypes:['loamy','sandy-loam','red'],
    states:['Gujarat','Rajasthan','Andhra Pradesh','Telangana','Karnataka'],
    optimal:  {N:[40,80],  P:[30,50],  K:[30,50],  ph:[6.0,7.5], temp:[25,35], humidity:[40,70], rainfall:[50,100]},
    tolerance:{N:[0,120],  P:[0,80],  K:[0,80],   ph:[5.5,8.5], temp:[18,42], humidity:[20,85], rainfall:[25,200]},
    agronomy:{
      sowingTime:'June–July (Kharif)',
      harvestTime:'November–December (180–210 days for hybrid)',
      waterNeeds:'Low to moderate — drought tolerant; 4–6 irrigations',
      fertilizerTip:'Apply 60:30:30 kg/ha N:P:K. Hybrid castor needs higher nutrition.',
      irrigationTip:'Apply at 30, 60, 90 DAS and spike (inflorescence) emergence.',
      organicTip:'FYM 5 t/acre improves castor oil content and root development.',
      tips:['Gujarat is India\'s #1 castor producer — GCH-4 hybrid is top variety','Stable global industrial demand — export price driven','Semilooper and capsule borer are major pests','Harvest when 1/3 of capsules on a spike turn brown'],
    },
    market:{demand:'High', priceStability:'Very High', mspAvailable:true, exportPotential:'Very High', riskLevel:'Low'},
    yield:{min:12, max:32, unit:'quintals/acre', avgIndia:20},
  },

  cotton: {
    name:'Cotton (Kapas)', emoji:'☁️', category:'Cash Crop',
    seasons:['kharif'],
    soilTypes:['black','clay-loam','loamy','alluvial'],
    states:['Gujarat','Maharashtra','Andhra Pradesh','Telangana','Haryana','Punjab','Karnataka','Rajasthan'],
    optimal:  {N:[80,120], P:[30,60],  K:[30,60],  ph:[6.0,8.0], temp:[25,37], humidity:[40,70], rainfall:[75,150]},
    tolerance:{N:[0,200],  P:[0,100], K:[0,100],  ph:[5.5,8.5], temp:[20,42], humidity:[25,85], rainfall:[40,300]},
    agronomy:{
      sowingTime:'April–June',
      harvestTime:'October–January (180–210 days)',
      waterNeeds:'Moderate to high — 8–10 irrigations; sensitive to drought at squaring/flowering',
      fertilizerTip:'Apply 100:50:50 kg/ha N:P:K. Boron 0.5 g/L foliar reduces boll shedding.',
      irrigationTip:'Critical: Squaring (45 DAS), Flowering (75 DAS), Boll development (100–130 DAS).',
      organicTip:'Mulching with cotton stalks conserves moisture and suppresses weeds.',
      tips:['Bt Cotton hybrids (Bollgard-II) have reduced bollworm pressure','Sucking pests (whitefly, thrips) are key threat — use yellow sticky traps','Boron + Magnesium foliar sprays reduce boll shedding','Do NOT over-irrigate — causes excess vegetative growth'],
    },
    market:{demand:'Very High', priceStability:'High', mspAvailable:true, exportPotential:'High', riskLevel:'Moderate'},
    yield:{min:10, max:30, unit:'quintals/acre (seed cotton)', avgIndia:18},
  },

  sugarcane: {
    name:'Sugarcane', emoji:'🎋', category:'Cash Crop',
    seasons:['year-round'],
    soilTypes:['loamy','clay-loam','alluvial','black'],
    states:['Uttar Pradesh','Maharashtra','Karnataka','Tamil Nadu','Bihar','Andhra Pradesh','Gujarat'],
    optimal:  {N:[120,180],P:[50,80],  K:[80,120], ph:[6.5,7.5], temp:[26,35], humidity:[60,80], rainfall:[150,250]},
    tolerance:{N:[0,300],  P:[0,120], K:[0,180],  ph:[5.5,8.0], temp:[18,40], humidity:[30,90], rainfall:[75,400]},
    agronomy:{
      sowingTime:'February–March (plant crop)',
      harvestTime:'November–January (12–18 months)',
      waterNeeds:'Very high — 1500–2500 mm seasonal',
      fertilizerTip:'Apply 250:80:100 kg/ha N:P:K in 4 split applications over the season.',
      irrigationTip:'Furrow or drip. Grand Growth Period (June–September) needs maximum water.',
      organicTip:'Trash mulching after harvest conserves moisture and adds organic matter.',
      tips:['Ratoon crop saves 40–50% input cost','Drip + fertigation saves 40% water and boosts yield 25%','Red rot and smut: use disease-free setts','Co-0238 (Karan-4) is the most popular variety'],
    },
    market:{demand:'Very High', priceStability:'Very High', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Low'},
    yield:{min:250, max:600, unit:'quintals/acre', avgIndia:350},
  },

  tomato: {
    name:'Tomato', emoji:'🍅', category:'Vegetable',
    seasons:['kharif','rabi','zaid'],
    soilTypes:['sandy-loam','loamy','alluvial'],
    states:[],
    optimal:  {N:[100,150],P:[50,80],  K:[80,120], ph:[6.0,7.0], temp:[20,30], humidity:[50,70], rainfall:[60,120]},
    tolerance:{N:[0,250],  P:[0,120], K:[0,180],  ph:[5.5,7.5], temp:[15,38], humidity:[30,90], rainfall:[30,250]},
    agronomy:{
      sowingTime:'Jun–Jul (Kharif) / Oct–Nov (Rabi) / Jan–Feb (Zaid)',
      harvestTime:'First harvest 70–90 days after transplanting',
      waterNeeds:'Moderate — drip irrigation strongly recommended',
      fertilizerTip:'Apply 120:60:80 kg/ha N:P:K. Calcium nitrate prevents Blossom End Rot.',
      irrigationTip:'Critical: Transplanting, fruit set, fruit development.',
      organicTip:'Vermicompost 2 t/acre at transplanting improves fruit quality.',
      tips:['Staking is essential — increases yield and reduces disease','Calcium Nitrate foliar (3 g/L) prevents Blossom End Rot','Drip + mulch saves 40% water','Early Blight scouting weekly is mandatory'],
    },
    market:{demand:'High', priceStability:'Low', mspAvailable:false, exportPotential:'Low', riskLevel:'High'},
    yield:{min:80, max:200, unit:'quintals/acre', avgIndia:120},
  },

  onion: {
    name:'Onion', emoji:'🧅', category:'Vegetable',
    seasons:['rabi','kharif'],
    soilTypes:['loamy','sandy-loam','alluvial'],
    states:['Maharashtra','Madhya Pradesh','Karnataka','Rajasthan','Gujarat','Bihar'],
    optimal:  {N:[60,100], P:[40,60],  K:[60,80],  ph:[6.0,7.0], temp:[13,24], humidity:[50,70], rainfall:[50,100]},
    tolerance:{N:[0,160],  P:[0,100], K:[0,120],  ph:[5.5,7.5], temp:[8,32],  humidity:[25,85], rainfall:[25,200]},
    agronomy:{
      sowingTime:'October–November (Rabi, main season)',
      harvestTime:'March–April (130–150 days from transplanting)',
      waterNeeds:'Moderate — 8–10 irrigations; critical at bulb development',
      fertilizerTip:'Apply 100:50:50 kg/ha N:P:K. Sulphur 30 kg/ha improves pungency and shelf life.',
      irrigationTip:'Stop irrigation 15–20 days before harvest for better curing.',
      organicTip:'Good K management gives hard, well-formed bulbs with long shelf life.',
      tips:['Nashik Red, Agrifound Light Red are popular varieties','Thrips is key pest — spray Spinosad if needed','Proper curing (7–10 days) essential for storage','Price volatility high — consider cold storage or FPO'],
    },
    market:{demand:'Very High', priceStability:'Low', mspAvailable:false, exportPotential:'High', riskLevel:'High'},
    yield:{min:60, max:160, unit:'quintals/acre', avgIndia:100},
  },

  potato: {
    name:'Potato', emoji:'🥔', category:'Vegetable',
    seasons:['rabi'],
    soilTypes:['sandy-loam','loamy','alluvial'],
    states:['Uttar Pradesh','West Bengal','Bihar','Punjab','Gujarat','Madhya Pradesh'],
    optimal:  {N:[80,120], P:[60,100], K:[100,150],ph:[5.0,6.5], temp:[14,24], humidity:[55,75], rainfall:[50,100]},
    tolerance:{N:[0,200],  P:[0,150], K:[0,200],  ph:[4.5,7.5], temp:[8,30],  humidity:[30,90], rainfall:[25,200]},
    agronomy:{
      sowingTime:'October–November',
      harvestTime:'February–March (70–120 days)',
      waterNeeds:'Moderate — 8–10 irrigations (500–700 mm)',
      fertilizerTip:'Apply 150:100:120 kg/ha N:P:K. Potassium is most critical.',
      irrigationTip:'Never allow moisture stress at tuber initiation (30–40 DAS) and bulking (50–80 DAS).',
      organicTip:'FYM 15 t/acre significantly improves tuber size and yield.',
      tips:['Kufri Jyoti, Kufri Bahar are popular varieties','Late Blight: preventive Metalaxyl spray at onset of fog/rain','Chitting seed tubers before planting improves emergence','Cold storage availability is key for market timing'],
    },
    market:{demand:'Very High', priceStability:'Moderate', mspAvailable:false, exportPotential:'Moderate', riskLevel:'Moderate'},
    yield:{min:80, max:200, unit:'quintals/acre', avgIndia:120},
  },

  banana: {
    name:'Banana', emoji:'🍌', category:'Fruit',
    seasons:['year-round'],
    soilTypes:['loamy','alluvial','clay-loam'],
    states:['Tamil Nadu','Gujarat','Maharashtra','Andhra Pradesh','Karnataka','Bihar','Madhya Pradesh'],
    optimal:  {N:[150,200],P:[50,80],  K:[200,300],ph:[6.0,7.5], temp:[25,35], humidity:[60,80], rainfall:[100,200]},
    tolerance:{N:[0,300],  P:[0,120], K:[0,400],  ph:[5.5,8.0], temp:[18,40], humidity:[40,95], rainfall:[50,400]},
    agronomy:{
      sowingTime:'Any month (tissue culture) — February–March preferred',
      harvestTime:'12–14 months from planting',
      waterNeeds:'High — drip irrigation strongly recommended (6–8 L/plant/day)',
      fertilizerTip:'Very high K demand. Apply 200:50:250 g/plant N:P:K over the crop period.',
      irrigationTip:'Drip with 6–8 L/plant/day. Critical: bunch development and filling.',
      organicTip:'Vermicompost 5 kg/plant/year dramatically improves fruit quality.',
      tips:['Grand Naine is the top commercial variety','Tissue culture plants give uniform yield and disease-free start','Potassium is #1 nutrient — K deficiency causes poor bunch weight','Panama Wilt: use resistant varieties and clean planting material'],
    },
    market:{demand:'Very High', priceStability:'Moderate', mspAvailable:false, exportPotential:'High', riskLevel:'Moderate'},
    yield:{min:200, max:500, unit:'quintals/acre', avgIndia:280},
  },

  cumin: {
    name:'Cumin (Jeera)', emoji:'🌿', category:'Spice',
    seasons:['rabi'],
    soilTypes:['sandy-loam','loamy','alluvial'],
    states:['Rajasthan','Gujarat'],
    optimal:  {N:[25,40],  P:[25,40],  K:[15,30],  ph:[6.5,8.0], temp:[14,22], humidity:[25,50], rainfall:[20,40]},
    tolerance:{N:[0,80],   P:[0,80],  K:[0,60],   ph:[6.0,8.5], temp:[8,28],  humidity:[10,65], rainfall:[10,80]},
    agronomy:{
      sowingTime:'November (after rains stop)',
      harvestTime:'February–March (95–115 days)',
      waterNeeds:'Low — 3–4 light irrigations; hates waterlogging',
      fertilizerTip:'Apply 30:25:15 kg/ha N:P:K. Excess N causes lodging and blight.',
      irrigationTip:'Light frequent irrigations — avoid heavy irrigation. Stop after grain fill.',
      organicTip:'FYM improves germination and stand establishment on sandy soils.',
      tips:['Blight (Alternaria) is the major threat — spray Mancozeb + Metalaxyl preventively','Harvest early morning when dew is present — reduces shattering loss','Unjha (Gujarat) is Asia\'s largest Jeera market','GC-4 and RZ-19 are recommended varieties'],
    },
    market:{demand:'High', priceStability:'Low', mspAvailable:false, exportPotential:'Very High', riskLevel:'High'},
    yield:{min:4, max:10, unit:'quintals/acre', avgIndia:6},
  },

  turmeric: {
    name:'Turmeric', emoji:'🟡', category:'Spice',
    seasons:['kharif'],
    soilTypes:['loamy','sandy-loam','red','laterite'],
    states:['Andhra Pradesh','Telangana','Tamil Nadu','Odisha','Karnataka','Maharashtra','Gujarat'],
    optimal:  {N:[80,120], P:[50,80],  K:[80,120], ph:[5.5,7.0], temp:[25,32], humidity:[65,85], rainfall:[150,250]},
    tolerance:{N:[0,200],  P:[0,120], K:[0,200],  ph:[4.5,8.0], temp:[18,40], humidity:[40,95], rainfall:[75,400]},
    agronomy:{
      sowingTime:'April–June (with Kharif rains)',
      harvestTime:'December–March (210–270 days)',
      waterNeeds:'High — 15–22 irrigations; never allow drought stress',
      fertilizerTip:'Apply 120:80:120 kg/ha N:P:K. Boron and Zinc foliar improve rhizome quality.',
      irrigationTip:'Keep field moist throughout; mulching reduces water need by 30%.',
      organicTip:'Leaf mulch (10 t/acre) is the traditional practice — dramatically improves yield.',
      tips:['Leaf mulching is highly effective — use sugarcane trash or dry leaves','Rhizome rot (Pythium): use Trichoderma-treated rhizomes','Curcumin content determines quality','Erode and Nizamabad are major trading centers'],
    },
    market:{demand:'High', priceStability:'Moderate', mspAvailable:false, exportPotential:'Very High', riskLevel:'Moderate'},
    yield:{min:40, max:120, unit:'quintals/acre (fresh)', avgIndia:60},
  },

  sesame: {
    name:'Sesame (Til)', emoji:'🌾', category:'Oilseed',
    seasons:['kharif','rabi','zaid'],
    soilTypes:['sandy-loam','loamy','red'],
    states:['Gujarat','Rajasthan','West Bengal','Andhra Pradesh','Tamil Nadu','Madhya Pradesh','Uttar Pradesh'],
    optimal:  {N:[30,50],  P:[25,40],  K:[20,35],  ph:[5.5,7.5], temp:[25,35], humidity:[35,65], rainfall:[40,80]},
    tolerance:{N:[0,100],  P:[0,80],  K:[0,70],   ph:[5.0,8.0], temp:[20,42], humidity:[20,85], rainfall:[20,150]},
    agronomy:{
      sowingTime:'June–July (Kharif) / Jan–Feb (Rabi in South)',
      harvestTime:'September–October (75–90 days)',
      waterNeeds:'Low — drought tolerant; 3–4 irrigations',
      fertilizerTip:'Apply 40:25:25 kg/ha N:P:K. Sulphur 10 kg/ha improves oil content.',
      irrigationTip:'Critical at branching (25–30 DAS) and capsule development (55–60 DAS).',
      organicTip:'Rhizobium seed treatment helps in sandy soils with low N.',
      tips:['Gujarat and Rajasthan are the main sesame-producing states','High oil content (50–55%) and premium export value','Gujarat Til-2, Pragati are popular varieties','Harvest when leaves turn yellow and lower capsules begin to split'],
    },
    market:{demand:'High', priceStability:'Moderate', mspAvailable:true, exportPotential:'Very High', riskLevel:'Moderate'},
    yield:{min:4, max:10, unit:'quintals/acre', avgIndia:6},
  },

  lentil: {
    name:'Lentil (Masoor)', emoji:'🫘', category:'Pulse',
    seasons:['rabi'],
    soilTypes:['loamy','clay-loam','alluvial'],
    states:['Uttar Pradesh','Madhya Pradesh','West Bengal','Bihar','Rajasthan'],
    optimal:  {N:[15,25],  P:[30,50],  K:[20,30],  ph:[6.0,7.0], temp:[15,25], humidity:[30,55], rainfall:[25,60]},
    tolerance:{N:[0,50],   P:[0,80],  K:[0,60],   ph:[5.5,8.0], temp:[8,30],  humidity:[15,75], rainfall:[15,120]},
    agronomy:{
      sowingTime:'October–November',
      harvestTime:'March–April (90–120 days)',
      waterNeeds:'Low — 2 irrigations (200–300 mm)',
      fertilizerTip:'Apply 20:40:20 kg/ha. Rhizobium inoculation essential.',
      irrigationTip:'Apply at branching and pod filling stage.',
      organicTip:'Rich in protein — leaves good residue for next crop.',
      tips:['Very low input requirements — good for resource-constrained farmers','Harvest when lower pods turn yellow-brown','Rust disease: Propiconazole spray','IPL-406, DPL-62 are recommended varieties'],
    },
    market:{demand:'High', priceStability:'Moderate', mspAvailable:true, exportPotential:'Moderate', riskLevel:'Moderate'},
    yield:{min:6, max:16, unit:'quintals/acre', avgIndia:9},
  },
}

// Soil types reference list
export const SOIL_TYPES = [
  {value:'alluvial',   label:'Alluvial (Domat)',   icon:'🟫'},
  {value:'black',      label:'Black Cotton',        icon:'⚫'},
  {value:'red',        label:'Red Laterite',        icon:'🔴'},
  {value:'sandy',      label:'Sandy (Baluee)',       icon:'🟡'},
  {value:'sandy-loam', label:'Sandy Loam',          icon:'🟤'},
  {value:'loamy',      label:'Loamy (Damat)',       icon:'🟤'},
  {value:'clay',       label:'Clay (Chiknee)',      icon:'🔵'},
  {value:'clay-loam',  label:'Clay Loam',           icon:'🟣'},
  {value:'laterite',   label:'Laterite',            icon:'🟠'},
]

export const CROP_KEYS = Object.keys(CROP_DB)