// backend/src/utils/schemesMockData.js
// ─────────────────────────────────────────────────────────
// Government agricultural scheme database.
// Sources: PM-KISAN, PMFBY, KCC, RKVY, PKVY, NMSA portals.
// Updated: May 2025
// ─────────────────────────────────────────────────────────

export const GOVERNMENT_SCHEMES = [

  // ══════════════════════════════════
  //  INCOME SUPPORT
  // ══════════════════════════════════
  {
    id: 'pm-kisan',
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    shortName: 'PM-KISAN',
    category: 'income_support',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2019,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '₹6,000/year',
    benefitType: 'Direct cash transfer',
    frequency: '₹2,000 every 4 months (3 instalments)',
    description: 'Provides income support of ₹6,000 per year to all land-holding farmer families in 3 equal instalments of ₹2,000 each, directly into bank accounts.',
    eligibility: [
      'All land-holding farmer families',
      'Own or cultivate agricultural land',
      'Valid Aadhaar card mandatory',
      'Valid bank account linked to Aadhaar',
    ],
    exclusions: [
      'Former/serving government employees',
      'Income tax payees',
      'Professionals like doctors, engineers, lawyers, chartered accountants',
      'Retired/pensioners receiving ≥₹10,000/month',
    ],
    documents: ['Aadhaar card', 'Land records (Khasra/Khatauni)', 'Bank passbook', 'Mobile number'],
    applyLink: 'https://pmkisan.gov.in',
    applyMode: ['Online (pmkisan.gov.in)', 'Common Service Centre (CSC)', 'Revenue officer/Patwari'],
    tags: ['cash transfer', 'income support', 'all farmers', 'aadhaar'],
    farmSizeApplicable: 'all',
    maxBenefitPerYear: 6000,
    icon: '💰',
  },

  // ══════════════════════════════════
  //  CROP INSURANCE
  // ══════════════════════════════════
  {
    id: 'pmfby',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    shortName: 'PMFBY',
    category: 'insurance',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2016,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: 'Up to ₹2 lakh/acre',
    benefitType: 'Crop insurance coverage',
    frequency: 'Per crop season (Kharif/Rabi/Zaid)',
    description: 'Comprehensive crop insurance covering losses from natural calamities, pests, diseases. Farmer pays only 2% premium for Kharif, 1.5% for Rabi crops. Government pays remaining premium.',
    eligibility: [
      'All farmers — loanee and non-loanee',
      'Sharecroppers and tenant farmers with land documents',
      'Must have Kisan Credit Card (KCC) recommended',
      'Enrolment before cutoff date (usually 31 July for Kharif)',
    ],
    exclusions: [
      'Risks due to war, nuclear risks',
      'Deliberate destruction',
      'Risks covered under other schemes',
    ],
    documents: ['Aadhaar', 'Bank account', 'Land records', 'Sown crop declaration', 'Mobile number'],
    applyLink: 'https://pmfby.gov.in',
    applyMode: ['Bank/KCC account', 'CSC centre', 'Insurance company agents', 'Online portal'],
    tags: ['insurance', 'crop protection', 'disaster relief', 'kharif', 'rabi'],
    farmSizeApplicable: 'all',
    premiumPercent: { kharif: 2, rabi: 1.5, horticulture: 5 },
    icon: '🛡️',
    highlights: ['Only 2% premium for Kharif', 'Government pays 98% premium', 'Covers drought, flood, hailstorm, pest, disease'],
  },

  {
    id: 'rwbcis',
    name: 'Restructured Weather Based Crop Insurance Scheme (RWBCIS)',
    shortName: 'RWBCIS',
    category: 'insurance',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2016,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: 'As per sum insured',
    benefitType: 'Weather-index based insurance',
    frequency: 'Per crop season',
    description: 'Insurance against weather adversities (rainfall, temperature, frost, humidity, wind) measured at automatic weather stations. Quick claim settlement without crop cutting experiments.',
    eligibility: ['All farmers in notified areas', 'Both loanee and non-loanee', 'Automatic weather stations must exist in area'],
    exclusions: ['Areas without automatic weather stations'],
    documents: ['Aadhaar', 'Bank account', 'Land records'],
    applyLink: 'https://pmfby.gov.in',
    applyMode: ['Bank', 'Insurance company', 'CSC'],
    tags: ['weather insurance', 'rainfall', 'quick settlement'],
    farmSizeApplicable: 'all',
    icon: '🌦️',
  },

  // ══════════════════════════════════
  //  CREDIT & LOANS
  // ══════════════════════════════════
  {
    id: 'kcc',
    name: 'Kisan Credit Card (KCC)',
    shortName: 'KCC',
    category: 'credit',
    ministry: 'Ministry of Agriculture & Farmers Welfare + RBI',
    launchedYear: 1998,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: 'Up to ₹3 lakh at 4% interest',
    benefitType: 'Revolving credit facility',
    frequency: 'Short-term (1 year), renewable',
    description: 'Provides adequate and timely credit for agricultural needs including cultivation, post-harvest, maintenance, and allied activities. Interest subvention of 2% + 3% prompt repayment incentive = effective rate 4%.',
    eligibility: [
      'Farmers owning or cultivating land',
      'Tenant farmers, sharecroppers',
      'Joint Liability Groups (JLGs)',
      'Self Help Groups (SHGs)',
    ],
    exclusions: ['Defaulters of any nationalised bank'],
    documents: ['Aadhaar', 'Land records', 'Passport photo', 'Application form from bank'],
    applyLink: 'https://www.nabard.org/content.aspx?id=572',
    applyMode: ['Any nationalised bank', 'Cooperative bank', 'RRB (Regional Rural Bank)', 'Online via bank portals'],
    tags: ['credit', 'loan', '4% interest', 'short-term', 'working capital'],
    farmSizeApplicable: 'all',
    maxLoanAmount: 300000,
    interestRate: 4,
    icon: '💳',
    highlights: ['Effective 4% interest with prompt payment', '₹3 lakh without collateral', 'Includes accident insurance of ₹50,000'],
  },

  // ══════════════════════════════════
  //  SUBSIDY SCHEMES
  // ══════════════════════════════════
  {
    id: 'nfsm',
    name: 'National Food Security Mission (NFSM)',
    shortName: 'NFSM',
    category: 'subsidy',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2007,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '50% subsidy on seeds, fertilizers, tools',
    benefitType: 'Input subsidy',
    frequency: 'Per crop season',
    description: 'Increases production of Rice, Wheat, Pulses, Coarse Cereals by area expansion, productivity enhancement. Covers seed, nutrient management, soil health, water use efficiency components.',
    eligibility: [
      'Farmers in notified districts',
      'Small and marginal farmers priority',
      'Farmers registered with Agriculture Department',
    ],
    exclusions: ['Areas not notified under NFSM'],
    documents: ['Farmer registration', 'Aadhaar', 'Land records'],
    applyLink: 'https://nfsm.gov.in',
    applyMode: ['Local Agriculture Department', 'District Agriculture Officer'],
    tags: ['food security', 'wheat', 'rice', 'pulses', 'seed subsidy'],
    farmSizeApplicable: 'small_marginal',
    icon: '🌾',
  },

  {
    id: 'smam',
    name: 'Sub Mission on Agricultural Mechanisation (SMAM)',
    shortName: 'SMAM',
    category: 'subsidy',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2014,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '40–50% subsidy on farm machinery',
    benefitType: 'Machinery subsidy',
    frequency: 'One-time per machine type',
    description: 'Provides 40–50% subsidy for purchase of farm machinery including tractors, power tillers, combine harvesters, threshers, sprayers. SC/ST and women farmers get additional 10% subsidy.',
    eligibility: [
      'All farmers',
      'Farmer cooperatives and FPOs',
      'SC/ST and women farmers get extra 10%',
    ],
    exclusions: ['Government farms', 'Those who received subsidy in last 3 years for same equipment'],
    documents: ['Aadhaar', 'Land records', 'Caste certificate (if SC/ST)', 'Bank account'],
    applyLink: 'https://agrimachinery.nic.in',
    applyMode: ['Online: agrimachinery.nic.in', 'District Agriculture Office'],
    tags: ['machinery', 'tractor', 'mechanisation', 'subsidy', 'equipment'],
    farmSizeApplicable: 'all',
    subsidyPercent: { general: 40, sc_st_women: 50 },
    icon: '🚜',
    highlights: ['40% subsidy (50% for SC/ST/Women)', 'Online application portal', 'Custom hiring centre support'],
  },

  {
    id: 'pkvy',
    name: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    shortName: 'PKVY',
    category: 'organic_farming',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2015,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '₹50,000/hectare over 3 years',
    benefitType: 'Financial assistance for organic farming',
    frequency: '₹16,667/hectare/year for 3 years',
    description: 'Promotes organic farming through cluster approach. Groups of 50 farmers (50 acres) form clusters and get ₹50,000/ha support for 3 years for conversion to certified organic farming.',
    eligibility: [
      'Minimum cluster of 50 farmers with 50 acres',
      'Commitment to 3-year organic conversion',
      'Registration with PGCS (Participatory Guarantee System)',
    ],
    exclusions: ['Individual farmers (must form cluster)'],
    documents: ['Farmer group formation', 'Land records', 'Aadhaar', 'Bank accounts of all members'],
    applyLink: 'https://pgsindia-ncof.gov.in',
    applyMode: ['District Agriculture Officer', 'ATMA (Agricultural Technology Management Agency)'],
    tags: ['organic', 'certification', 'sustainable', 'cluster farming'],
    farmSizeApplicable: 'all',
    icon: '🌿',
    highlights: ['₹50,000/hectare for 3 years', 'Free organic certification', 'Market linkage support'],
  },

  {
    id: 'nmsa',
    name: 'National Mission for Sustainable Agriculture (NMSA)',
    shortName: 'NMSA',
    category: 'soil_water',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2014,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '50–75% subsidy on soil, water conservation works',
    benefitType: 'Infrastructure subsidy',
    frequency: 'Per application',
    description: 'Supports soil health management, water use efficiency, climate change adaptation including drip/sprinkler irrigation subsidies, soil health card implementation.',
    eligibility: ['All farmers in notified areas', 'Priority to small/marginal farmers'],
    exclusions: ['Large commercial farms may have reduced benefits'],
    documents: ['Aadhaar', 'Land records', 'Soil Health Card (preferred)'],
    applyLink: 'https://nmsa.dac.gov.in',
    applyMode: ['District Agriculture Officer'],
    tags: ['soil health', 'water conservation', 'drip irrigation', 'climate'],
    farmSizeApplicable: 'all',
    icon: '💧',
  },

  {
    id: 'pmksy',
    name: 'PM Krishi Sinchai Yojana – Per Drop More Crop',
    shortName: 'PMKSY-PDMC',
    category: 'irrigation',
    ministry: 'Ministry of Jal Shakti',
    launchedYear: 2015,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '55–75% subsidy on micro-irrigation',
    benefitType: 'Drip/Sprinkler irrigation subsidy',
    frequency: 'One-time',
    description: 'Provides 55% subsidy for small/marginal farmers and 45% for other farmers on drip and sprinkler irrigation systems. Target: Har Khet Ko Pani, More Crop Per Drop.',
    eligibility: [
      'All farmers owning agricultural land',
      'Small/marginal farmers: 55% subsidy',
      'Other farmers: 45% subsidy',
      'SC/ST farmers: additional 10% state supplement in many states',
    ],
    exclusions: ['Those who received subsidy in last 5 years for same system'],
    documents: ['Aadhaar', 'Land records', 'Bank account', 'Quote from approved vendor'],
    applyLink: 'https://pmksy.gov.in',
    applyMode: ['State Agriculture Department', 'District Agriculture Officer', 'Online state portals'],
    tags: ['irrigation', 'drip', 'sprinkler', 'water efficiency', 'subsidy'],
    farmSizeApplicable: 'all',
    subsidyPercent: { small_marginal: 55, others: 45 },
    icon: '🌊',
    highlights: ['55% subsidy for small/marginal farmers', 'Approved vendor empanelled list', 'Quick processing in most states'],
  },

  // ══════════════════════════════════
  //  MARKET LINKAGE
  // ══════════════════════════════════
  {
    id: 'enam',
    name: 'e-NAM (National Agriculture Market)',
    shortName: 'e-NAM',
    category: 'market_access',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2016,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: 'Better price discovery, reduced commission',
    benefitType: 'Online trading platform',
    frequency: 'Ongoing',
    description: 'Pan-India electronic trading portal for agricultural commodities. Allows farmers to sell directly to buyers across India, improving price discovery and reducing intermediaries.',
    eligibility: ['Farmers in e-NAM integrated mandis', 'Must have smartphone or access to CSC'],
    exclusions: ['Areas without integrated APMCs'],
    documents: ['Aadhaar', 'Bank account', 'Mobile number'],
    applyLink: 'https://enam.gov.in',
    applyMode: ['enam.gov.in registration', 'CSC centre', 'Mandi office'],
    tags: ['online market', 'price discovery', 'direct selling', 'APMC'],
    farmSizeApplicable: 'all',
    icon: '📱',
  },

  {
    id: 'fpo-scheme',
    name: 'Formation & Promotion of 10,000 FPOs',
    shortName: 'FPO Promotion',
    category: 'collective_farming',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2020,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '₹18 lakh/FPO over 3 years + equity grant',
    benefitType: 'Financial and technical support to farmer groups',
    frequency: '3-year support',
    description: 'Formation of Farmer Producer Organisations with financial support of ₹18 lakh per FPO. Includes management cost, equity grant, credit guarantee fund, and market linkage.',
    eligibility: [
      'Minimum 300 members (100 in NE/hilly areas)',
      'Must register as FPC under Companies Act',
      'Must elect Board of Directors',
    ],
    exclusions: ['Individual farmers — must form group'],
    documents: ['Group formation documents', 'Member Aadhaar', 'Land records of members'],
    applyLink: 'https://sfac.in/fpo.php',
    applyMode: ['SFAC', 'NABARD', 'State Cooperative Departments'],
    tags: ['FPO', 'collective farming', 'market access', 'group farming'],
    farmSizeApplicable: 'all',
    icon: '🤝',
  },

  // ══════════════════════════════════
  //  STATE-SPECIFIC SCHEMES
  // ══════════════════════════════════
  {
    id: 'gujarat-ikhedut',
    name: 'i-Khedut Portal Schemes (Gujarat)',
    shortName: 'i-Khedut',
    category: 'subsidy',
    ministry: 'Gujarat Agriculture Department',
    launchedYear: 2013,
    status: 'active',
    level: 'state',
    states: ['Gujarat'],
    benefitAmount: 'Various — seeds, machinery, irrigation subsidies',
    benefitType: 'Multiple input subsidies',
    frequency: 'Per season/application',
    description: 'Gujarat government\'s single-window portal for all agricultural subsidies including seeds, fertilizers, irrigation equipment, farm machinery, and horticulture support.',
    eligibility: ['Gujarat farmers with land records', 'Aadhaar and bank account'],
    exclusions: ['Non-Gujarat residents'],
    documents: ['Aadhaar', '7/12 Utara (land record)', 'Bank passbook', '8A document'],
    applyLink: 'https://ikhedut.gujarat.gov.in',
    applyMode: ['Online: ikhedut.gujarat.gov.in', 'Common Service Centre'],
    tags: ['gujarat', 'state scheme', 'ikhedut', 'multiple subsidies'],
    farmSizeApplicable: 'all',
    icon: '🏛️',
    highlights: ['Single window for 40+ schemes', 'Online application', 'Status tracking'],
  },

  {
    id: 'maharashtra-magel-tyal-sheti',
    name: 'Magel Tyala Sheti Pump (Maharashtra)',
    shortName: 'Pump Scheme MH',
    category: 'irrigation',
    ministry: 'Maharashtra Agriculture Department',
    launchedYear: 2019,
    status: 'active',
    level: 'state',
    states: ['Maharashtra'],
    benefitAmount: '100% electricity connection + 7.5 HP pump',
    benefitType: 'Irrigation pump subsidy',
    frequency: 'One-time',
    description: 'Provides free electricity connection and subsidised pump sets to farmers. Over 100,000 farmers covered.',
    eligibility: ['Maharashtra farmers without electricity connection', 'Agricultural land required'],
    exclusions: ['Farmers already having electricity connection'],
    documents: ['7/12 extract', 'Aadhaar', 'Electricity bill of another consumer at address'],
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    applyMode: ['MahaDbt Portal', 'District Agriculture Office'],
    tags: ['maharashtra', 'irrigation', 'pump', 'electricity'],
    farmSizeApplicable: 'all',
    icon: '⚡',
  },

  {
    id: 'punjab-msp-bonus',
    name: 'Punjab Crop Residue Management Scheme',
    shortName: 'CRM Punjab',
    category: 'subsidy',
    ministry: 'Punjab Agriculture Department',
    launchedYear: 2018,
    status: 'active',
    level: 'state',
    states: ['Punjab'],
    benefitAmount: '₹2,500/acre subsidy on residue management',
    benefitType: 'Crop residue management incentive',
    frequency: 'Per season (Kharif)',
    description: 'Financial incentive to farmers for in-situ management of paddy straw instead of burning. Reduces air pollution while providing income to farmers.',
    eligibility: ['Punjab paddy farmers', 'Must not burn crop residue', 'Village-level verification'],
    exclusions: ['Farmers who burn crop residue', 'Non-paddy crops'],
    documents: ['Aadhaar', 'Land records', 'Girdawari (crop inspection report)'],
    applyLink: 'https://agripb.gov.in',
    applyMode: ['Gram Panchayat office', 'Agriculture Department block office'],
    tags: ['punjab', 'paddy', 'stubble', 'environment', 'incentive'],
    farmSizeApplicable: 'all',
    icon: '🌱',
  },

  // ══════════════════════════════════
  //  WELFARE SCHEMES
  // ══════════════════════════════════
  {
    id: 'pm-kmy',
    name: 'PM Kisan Mandhan Yojana (PM-KMY)',
    shortName: 'PM-KMY',
    category: 'pension',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    launchedYear: 2019,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '₹3,000/month pension after age 60',
    benefitType: 'Pension scheme',
    frequency: 'Monthly pension after 60',
    description: 'Voluntary pension scheme for small and marginal farmers. Government matches farmer\'s contribution. On reaching age 60, farmer gets ₹3,000/month guaranteed pension.',
    eligibility: [
      'Small and marginal farmers (up to 2 hectares)',
      'Age 18–40 years at time of enrolment',
      'Not covered under EPFO, ESIC, NPS, PMVVY',
    ],
    exclusions: ['Large farmers (above 2 ha)', 'Above 40 years age', 'Government employees'],
    documents: ['Aadhaar', 'Bank account', 'Mobile number', 'Age proof'],
    applyLink: 'https://pmkmy.gov.in',
    applyMode: ['CSC centres', 'Online enrollment', 'Any branch of Life Insurance Corporation'],
    tags: ['pension', 'retirement', 'small farmers', 'social security'],
    farmSizeApplicable: 'small_marginal',
    contribution: { age18to29: 55, age30to39: 100, age40to: 200 },
    icon: '👴',
    highlights: ['Govt matches your contribution', '₹3,000/month at age 60', 'Auto-debit from bank account'],
  },

  {
    id: 'pmegp',
    name: 'PM Employment Generation Programme (PMEGP)',
    shortName: 'PMEGP',
    category: 'agro_enterprise',
    ministry: 'Ministry of MSME',
    launchedYear: 2008,
    status: 'active',
    level: 'central',
    states: 'all',
    benefitAmount: '15–35% subsidy on project cost',
    benefitType: 'Entrepreneurship subsidy for agro-processing',
    frequency: 'One-time',
    description: 'Provides financial assistance to set up micro-enterprises in agriculture processing, food processing, and allied activities. 15% subsidy (urban), 25% (rural), 35% for SC/ST/women in rural.',
    eligibility: [
      'Individuals above 18 years',
      'Educational qualification: VIII pass for projects above ₹10 lakh',
      'Priority: farmers, rural youth, SC/ST, women',
    ],
    exclusions: ['Existing enterprises', 'Tobacco/liquor businesses'],
    documents: ['Aadhaar', 'Educational certificate', 'Project report', 'Bank sanction letter'],
    applyLink: 'https://kviconline.gov.in/pmegpeportal',
    applyMode: ['Online portal', 'KVIC/KVIB/DIC offices'],
    tags: ['agro-processing', 'food processing', 'enterprise', 'rural employment'],
    farmSizeApplicable: 'all',
    subsidyPercent: { urban_general: 15, rural_general: 25, sc_st_women_rural: 35 },
    icon: '🏭',
  },
]

// ── Scheme categories ─────────────────────────────────────
export const SCHEME_CATEGORIES = [
  { id: 'all',             label: 'All Schemes',        icon: '📋' },
  { id: 'income_support',  label: 'Income Support',     icon: '💰' },
  { id: 'insurance',       label: 'Crop Insurance',     icon: '🛡️' },
  { id: 'credit',          label: 'Credit & Loans',     icon: '💳' },
  { id: 'subsidy',         label: 'Subsidies',          icon: '🎁' },
  { id: 'irrigation',      label: 'Irrigation',         icon: '💧' },
  { id: 'organic_farming', label: 'Organic Farming',    icon: '🌿' },
  { id: 'market_access',   label: 'Market Access',      icon: '📱' },
  { id: 'pension',         label: 'Pension & Welfare',  icon: '👴' },
  { id: 'agro_enterprise', label: 'Agro Enterprise',    icon: '🏭' },
]

// ── Eligibility tags for smart matching ──────────────────
export const FARMER_PROFILES = [
  { id: 'small',    label: 'Small Farmer (< 1 ha)',    maxHa: 1   },
  { id: 'marginal', label: 'Marginal Farmer (1–2 ha)', maxHa: 2   },
  { id: 'medium',   label: 'Medium Farmer (2–5 ha)',   maxHa: 5   },
  { id: 'large',    label: 'Large Farmer (> 5 ha)',    maxHa: 999 },
]